# Projet d'optimisation 
## Par  Rania Fathi et Pierre Sion 

## I- Modélisation 

### Question 1 :
On définit l'élasticité-prix comme étant la variation relative de la quantité demandée par rapport au prix, soit encore: 
    $\varepsilon_i = \frac{\frac{dx_i}{x_i}}{\frac{dp_i}{p_i}} $ 
où l'on a noté $x_i$ la demande et $p_i$ le prix du ième produit 
    
Cela peut encore s'écrire: 
$\varepsilon_i = \frac{\partial x_i}{\partial p_i} \frac{p_i}{x_i}$

Comme on s'attend à ce que la demande pour un produit diminue si le prix augmente, on a $\varepsilon_i \leq 0$

Pour ce qui est de l'élasticité prix croisée entre le gouda et l'edam, elle vaut: 

$\varepsilon_c = \frac{\frac{dx_g}{x_g}}{\frac{dp_e}{p_e}} = \frac{\partial x_g}{\partial p_e} \frac{p_e}{x_g}$

Les biens considérés étant substituables, on a $\varepsilon_c \geq 0$ 

### Question 2 :
Le lait brut possède une quantité de matière grasse totale répartie entre les quatre produits, que l'on note $M$. En notant $m_i$ la teneur en matière grasse présente dans chaque produit, on a : 

$ \sum_{i=1}^{4}m_i x_i \leq M$

On fait par ailleurs le choix de mettre une inégalité plutôt qu'une égalité pour considérer le cas où tout le lait n'est pas transformé 

### Question 3 : 
De la même manière, on note $L$ la quantité totale de lactose contenue dans le lait, et $l_i$ celle contenue dans chaque produit, et on a alors la contrainte suivante: 

$\sum_{i=1}^{4} l_i x_i \leq L $

### Question 4 :

Afin de garantir la paix sociale, la moyenne (pondérée par la part de chaque produit dans le budget) des changements de prix relatifs ne doit pas être positive.
On note $b_i$ la part du ième produit dans le budget (déterminée à partir des données de l'année N-1). Cette contrainte s'écrit donc: 
$\sum_{i=1}^{4}b_i \frac{dp_i}{p_i} \leq 0$

Comme les contraintes dont on dispose jusque maintenant portent sur les quantités et non pas les prix, on la réécrit sous la forme suivante : $ \sum_{i=1}^4 \frac{b_i}{\epsilon_i} \frac{dx_i}{x_i} \leq 0$ 

### Question 5 :

_En supposant qu'on dispose déjà des $(p_i)_{1\leq i\leq4}$, $(b_i)_{1\leq i\leq4}$, $(\epsilon_i)_{1\leq i\leq4}$, $(m_i)_{1\leq i \leq 4}$, de $M$ et $L$_  
On dispose donc du problème d'optimisation sous contraintes suivant : $\max_{c(x) \leq 0} \Pi (x)$ 

où le profit $\Pi:\mathbf{R}^4 \rightarrow \mathbf{R}  $ vaut $\Pi(x) = \sum_{i=1}^4 p_i x_i $ (En toute rigueur, $\Pi$ est égal au revenu plutôt qu'au profit, mais l'omission du terme $-C$ correspondant au coût total du lait acheté ne modifie pas le problème d'optimisation à résoudre).

Et les contraintes $c : \mathbf{R}^4 \rightarrow \mathbf{R}^7$ sont les suivantes : 

$c_1(x) = - x_1 \\ 
c_2(x) = - x_2\\ 
c_3(x) = - x_3\\ 
c_4(x) = - x_4$

Ces quatre premières contraintes traduisent le fait que les quantités considérées sont nécessairement positives. Et nous disposons des deux contraintes des questions 2 et 3: 

$c_5(x) = \sum_{i=1}^{4}m_i x_i - M\\ 
c_6(x) = \sum_{i=1}^{4} l_i x_i - L $

Et enfin :
$c_7(x) =  \sum_{i=1}^4 \frac{b_i}{\epsilon_i} \frac{dx_i}{x_i} \leq 0$

NB: Il aurait été possible d'ajouter les contraintes portant sur le signe de l'élasticité des produits, imposant que l'augmentation du prix d'un produit réduit la demande, ou encore celles stipulant que les prix des produits se doivent d'être positifs 

## II- Implémentation 

### Cadre de travail

In [6]:
import numpy as np


A = np.array([[3.0825,0,0,0],
              [0,0.0405,0,0,],
              [0,0,0.0271,-0.0031],
              [0,0,-0.0031,0.0054]])
b = np.array([2671,135,103,19])

C = np.array([[-0.0401,-0.0162,-0.0039,0.0002],
              [-0.1326,-0.0004,-0.0034,0.0006],
              [1.5413,0,0,0],
              [0,0.0203,0,0],
              [0,0,0.0136,-0.0015],
              [0,0,-0.0016,0.0027],
              [0.0160,0.0004,0.0005,0.0002]])

d = np.array([-92.6,-29,2671,135,103,19,10])

### Première méthode : Algorithme de Arrow-Hurwickz

On commence par construire le projecteur sur $\mathbb{R}_{+}$ :

In [7]:
def proj(x):
    for i in range(0,len(x)):
        if x[i]<0:
            x[i]=0
    return x

Ce qui permet d'implémenter l'algorithme AH : 

In [8]:
P0=np.array([2055,54,63,17])

LAMBDA=np.array([1,1,1,1,1,1,1])

def algo_ah(p0=P0,lambda0=LAMBDA,epsilon=0.01,mu=10**-5,alpha=0.001):   
    l=lambda0
    pl=p0
    pk=pl-epsilon*(b-np.dot(A,pl)+(np.transpose(C)).dot(l))
    while(np.linalg.norm(pk-pl)>mu):
        pl=pk
        pk=pk-epsilon*(b-np.dot(A,pk)+(np.transpose(C)).dot(l))
        l=proj(l+alpha*(np.dot(C,pk)-d))
        print(pk)
    return pk

In [9]:
print(algo_ah())

[2129.37191663   51.34312009   60.97271926   16.6179071 ]
[2168.27620497   50.01390013   59.95868081   16.42689276]
[2208.36903125   48.68416865   58.94437832   16.23590001]
[2249.68607191   47.35392517   57.92981149   16.0449289 ]
[2292.26413463   46.02316937   56.91498156   15.85397919]
[2336.1413747    44.69190168   55.89989598   15.66304956]
[2381.35679612   43.36012162   54.88455461   15.47214002]
[2427.95057335   42.02782867   53.86895733   15.28125058]
[2475.96408646   40.69500765   52.85310397   15.09038124]
[2525.43995732   39.3616455    51.83699441   14.89953203]
[2576.42208685   38.02774167   50.82062541   14.70870328]
[2628.95569338   36.69329562   49.80398598   14.51789622]
[2683.08735225   35.35830679   48.78707596   14.32711084]
[2738.86503645   34.0227746    47.76989519   14.13634716]
[2796.33815864   32.68669847   46.75244351   13.9456052 ]
[2855.5576143    31.35007782   45.73472074   13.75488496]
[2916.57582623   30.01291203   44.71672671   13.56418646]
[2979.44679042

[ 1.79547305e+14 -1.33237292e+07 -1.65720458e+07 -6.56613970e+06]
[ 1.84935437e+14 -1.37235302e+07 -1.70693387e+07 -6.76318250e+06]
[ 1.90485264e+14 -1.41353290e+07 -1.75815551e+07 -6.96613845e+06]
[ 1.96201639e+14 -1.45594856e+07 -1.81091428e+07 -7.17518502e+06]
[ 2.02089560e+14 -1.49963709e+07 -1.86525632e+07 -7.39050497e+06]
[ 2.08154175e+14 -1.54463668e+07 -1.92122913e+07 -7.61228657e+06]
[ 2.14400786e+14 -1.59098669e+07 -1.97888165e+07 -7.84072372e+06]
[ 2.20834854e+14 -1.63872763e+07 -2.03826430e+07 -8.07601617e+06]
[ 2.27462007e+14 -1.68790126e+07 -2.09942899e+07 -8.31836962e+06]
[ 2.34288037e+14 -1.73855055e+07 -2.16242920e+07 -8.56799599e+06]
[ 2.41318913e+14 -1.79071980e+07 -2.22732002e+07 -8.82511353e+06]
[ 2.48560782e+14 -1.84445462e+07 -2.29415817e+07 -9.08994704e+06]
[ 2.56019977e+14 -1.89980200e+07 -2.36300210e+07 -9.36272807e+06]
[ 2.63703018e+14 -1.95681031e+07 -2.43391200e+07 -9.64369514e+06]
[ 2.71616624e+14 -2.01552942e+07 -2.50694988e+07 -9.93309389e+06]
[ 2.797677

[ 1.75005497e+23 -1.29853983e+16 -1.61519371e+16 -6.39990698e+15]
[ 1.80257331e+23 -1.33750841e+16 -1.66366493e+16 -6.59196524e+15]
[ 1.85666771e+23 -1.37764642e+16 -1.71359075e+16 -6.78978708e+15]
[ 1.91238545e+23 -1.41898896e+16 -1.76501482e+16 -6.99354546e+15]
[ 1.96977525e+23 -1.46157216e+16 -1.81798210e+16 -7.20341854e+15]
[ 2.02888730e+23 -1.50543327e+16 -1.87253890e+16 -7.41958981e+15]
[ 2.08977328e+23 -1.55061063e+16 -1.92873293e+16 -7.64224828e+15]
[ 2.15248641e+23 -1.59714374e+16 -1.98661332e+16 -7.87158863e+15]
[ 2.21708153e+23 -1.64507329e+16 -2.04623067e+16 -8.10781138e+15]
[ 2.28361513e+23 -1.69444118e+16 -2.10763711e+16 -8.35112306e+15]
[ 2.35214537e+23 -1.74529058e+16 -2.17088633e+16 -8.60173641e+15]
[ 2.42273217e+23 -1.79766594e+16 -2.23603362e+16 -8.85987056e+15]
[ 2.49543724e+23 -1.85161307e+16 -2.30313596e+16 -9.12575119e+15]
[ 2.57032416e+23 -1.90717912e+16 -2.37225201e+16 -9.39961078e+15]
[ 2.64745841e+23 -1.96441269e+16 -2.44344220e+16 -9.68168877e+15]
[ 2.726907

[ 3.28132445e+33 -2.43474095e+26 -3.02846179e+26 -1.19997209e+26]
[ 3.37979548e+33 -2.50780640e+26 -3.11934453e+26 -1.23598270e+26]
[ 3.48122159e+33 -2.58306451e+26 -3.21295463e+26 -1.27307397e+26]
[ 3.58569144e+33 -2.66058109e+26 -3.30937391e+26 -1.31127834e+26]
[ 3.69329639e+33 -2.74042390e+26 -3.40868670e+26 -1.35062920e+26]
[ 3.80413051e+33 -2.82266276e+26 -3.51097982e+26 -1.39116096e+26]
[ 3.91829072e+33 -2.90736957e+26 -3.61634270e+26 -1.43290905e+26]
[ 4.03587682e+33 -2.99461839e+26 -3.72486748e+26 -1.47591000e+26]
[ 4.15699162e+33 -3.08448551e+26 -3.83664904e+26 -1.52020137e+26]
[ 4.28174102e+33 -3.17704950e+26 -3.95178511e+26 -1.56582192e+26]
[ 4.41023410e+33 -3.27239129e+26 -4.07037636e+26 -1.61281151e+26]
[ 4.54258319e+33 -3.37059424e+26 -4.19252648e+26 -1.66121124e+26]
[ 4.67890402e+33 -3.47174422e+26 -4.31834227e+26 -1.71106343e+26]
[ 4.81931577e+33 -3.57592967e+26 -4.44793373e+26 -1.76241165e+26]
[ 4.96394122e+33 -3.68324167e+26 -4.58141417e+26 -1.81530081e+26]
[ 5.112906

[ 2.24298831e+42 -1.66429610e+35 -2.07014104e+35 -8.20255181e+34]
[ 2.31029936e+42 -1.71424086e+35 -2.13226502e+35 -8.44870661e+34]
[ 2.37963038e+42 -1.76568444e+35 -2.19625331e+35 -8.70224840e+34]
[ 2.45104199e+42 -1.81867182e+35 -2.26216186e+35 -8.96339887e+34]
[ 2.52459663e+42 -1.87324932e+35 -2.33004829e+35 -9.23238634e+34]
[ 2.60035861e+42 -1.92946467e+35 -2.39997197e+35 -9.50944600e+34]
[ 2.67839417e+42 -1.98736701e+35 -2.47199402e+35 -9.79482009e+34]
[ 2.75877155e+42 -2.04700698e+35 -2.54617742e+35 -1.00887581e+35]
[ 2.84156101e+42 -2.10843672e+35 -2.62258704e+35 -1.03915171e+35]
[ 2.92683495e+42 -2.17170993e+35 -2.70128966e+35 -1.07033618e+35]
[ 3.01466792e+42 -2.23688195e+35 -2.78235412e+35 -1.10245647e+35]
[ 3.10513671e+42 -2.30400974e+35 -2.86585129e+35 -1.13554068e+35]
[ 3.19832043e+42 -2.37315201e+35 -2.95185416e+35 -1.16961773e+35]
[ 3.29430056e+42 -2.44436921e+35 -3.04043795e+35 -1.20471742e+35]
[ 3.39316100e+42 -2.51772361e+35 -3.13168009e+35 -1.24087044e+35]
[ 3.494988

[ 9.83979712e+50 -7.30112409e+43 -9.08153098e+43 -3.59838905e+43]
[ 1.01350849e+51 -7.52022745e+43 -9.35406354e+43 -3.70637504e+43]
[ 1.04392341e+51 -7.74590602e+43 -9.63477468e+43 -3.81760165e+43]
[ 1.07525107e+51 -7.97835709e+43 -9.92390982e+43 -3.93216612e+43]
[ 1.10751886e+51 -8.21778391e+43 -1.02217218e+44 -4.05016861e+43]
[ 1.14075499e+51 -8.46439581e+43 -1.05284709e+44 -4.17171230e+43]
[ 1.17498852e+51 -8.71840843e+43 -1.08444255e+44 -4.29690347e+43]
[ 1.21024939e+51 -8.98004385e+43 -1.11698617e+44 -4.42585156e+43]
[ 1.24656842e+51 -9.24953083e+43 -1.15050641e+44 -4.55866933e+43]
[ 1.28397736e+51 -9.52710499e+43 -1.18503258e+44 -4.69547289e+43]
[ 1.32250893e+51 -9.81300902e+43 -1.22059486e+44 -4.83638187e+43]
[ 1.36219681e+51 -1.01074929e+44 -1.25722435e+44 -4.98151946e+43]
[ 1.40307571e+51 -1.04108141e+44 -1.29495307e+44 -5.13101257e+43]
[ 1.44518137e+51 -1.07232378e+44 -1.33381402e+44 -5.28499189e+43]
[ 1.48855059e+51 -1.10450373e+44 -1.37384116e+44 -5.44359206e+43]
[ 1.533221

[ 1.57958458e+59 -1.17205089e+52 -1.45785996e+52 -5.77650105e+51]
[ 1.62698718e+59 -1.20722360e+52 -1.50160967e+52 -5.94985118e+51]
[ 1.67581232e+59 -1.24345182e+52 -1.54667228e+52 -6.12840347e+51]
[ 1.72610267e+59 -1.28076724e+52 -1.59308721e+52 -6.31231404e+51]
[ 1.77790222e+59 -1.31920248e+52 -1.64089502e+52 -6.50174368e+51]
[ 1.83125625e+59 -1.35879113e+52 -1.69013752e+52 -6.69685801e+51]
[ 1.88621140e+59 -1.39956783e+52 -1.74085777e+52 -6.89782763e+51]
[ 1.94281574e+59 -1.44156821e+52 -1.79310011e+52 -7.10482826e+51]
[ 2.00111874e+59 -1.48482901e+52 -1.84691022e+52 -7.31804088e+51]
[ 2.06117139e+59 -1.52938805e+52 -1.90233514e+52 -7.53765192e+51]
[ 2.12302620e+59 -1.57528428e+52 -1.95942334e+52 -7.76385338e+51]
[ 2.18673724e+59 -1.62255783e+52 -2.01822474e+52 -7.99684304e+51]
[ 2.25236021e+59 -1.67125005e+52 -2.07879073e+52 -8.23682461e+51]
[ 2.31995250e+59 -1.72140349e+52 -2.14117428e+52 -8.48400793e+51]
[ 2.38957321e+59 -1.77306202e+52 -2.20542994e+52 -8.73860909e+51]
[ 2.461283

[ 9.31353362e+67 -6.91063686e+60 -8.59582196e+60 -3.40593581e+60]
[ 9.59302848e+67 -7.11802189e+60 -8.85377861e+60 -3.50814637e+60]
[ 9.88091084e+67 -7.33163044e+60 -9.11947643e+60 -3.61342423e+60]
[ 1.01774324e+68 -7.55164929e+60 -9.39314771e+60 -3.72186143e+60]
[ 1.04828525e+68 -7.77827081e+60 -9.67503175e+60 -3.83355277e+60]
[ 1.07974381e+68 -8.01169313e+60 -9.96537499e+60 -3.94859592e+60]
[ 1.11214642e+68 -8.25212035e+60 -1.02644313e+61 -4.06709147e+60]
[ 1.14552142e+68 -8.49976268e+60 -1.05724622e+61 -4.18914301e+60]
[ 1.17989799e+68 -8.75483664e+60 -1.08897369e+61 -4.31485726e+60]
[ 1.21530619e+68 -9.01756526e+60 -1.12165329e+61 -4.44434414e+60]
[ 1.25177696e+68 -9.28817824e+60 -1.15531358e+61 -4.57771686e+60]
[ 1.28934221e+68 -9.56691218e+60 -1.18998401e+61 -4.71509203e+60]
[ 1.32803478e+68 -9.85401081e+60 -1.22569488e+61 -4.85658977e+60]
[ 1.36788849e+68 -1.01497251e+61 -1.26247742e+61 -5.00233379e+60]
[ 1.40893820e+68 -1.04543137e+61 -1.30036379e+61 -5.15245153e+60]
[ 1.451219

[ 5.65623358e+76 -4.19692222e+69 -5.22035768e+69 -2.06847039e+69]
[ 5.82597454e+76 -4.32286993e+69 -5.37701821e+69 -2.13054423e+69]
[ 6.00080936e+76 -4.45259726e+69 -5.53838005e+69 -2.19448088e+69]
[ 6.18089088e+76 -4.58621765e+69 -5.70458428e+69 -2.26033624e+69]
[ 6.36637657e+76 -4.72384793e+69 -5.87577623e+69 -2.32816789e+69]
[ 6.55742859e+76 -4.86560843e+69 -6.05210557e+69 -2.39803513e+69]
[ 6.75421400e+76 -5.01162310e+69 -6.23372647e+69 -2.46999906e+69]
[ 6.95690485e+76 -5.16201960e+69 -6.42079772e+69 -2.54412260e+69]
[ 7.16567836e+76 -5.31692943e+69 -6.61348291e+69 -2.62047055e+69]
[ 7.38071707e+76 -5.47648803e+69 -6.81195048e+69 -2.69910966e+69]
[ 7.60220899e+76 -5.64083491e+69 -7.01637397e+69 -2.78010870e+69]
[ 7.83034778e+76 -5.81011377e+69 -7.22693212e+69 -2.86353848e+69]
[ 8.06533291e+76 -5.98447261e+69 -7.44380903e+69 -2.94947195e+69]
[ 8.30736983e+76 -6.16406387e+69 -7.66719431e+69 -3.03798424e+69]
[ 8.55667017e+76 -6.34904459e+69 -7.89728328e+69 -3.12915275e+69]
[ 8.813451

[ 1.41482518e+85 -1.04979951e+78 -1.30579711e+78 -5.17398006e+77]
[ 1.45728343e+85 -1.08130351e+78 -1.34498348e+78 -5.32924882e+77]
[ 1.50101583e+85 -1.11375293e+78 -1.38534582e+78 -5.48917712e+77]
[ 1.54606063e+85 -1.14717614e+78 -1.42691941e+78 -5.65390480e+77]
[ 1.59245719e+85 -1.18160237e+78 -1.46974060e+78 -5.82357588e+77]
[ 1.64024610e+85 -1.21706171e+78 -1.51384684e+78 -5.99833871e+77]
[ 1.68946913e+85 -1.25358517e+78 -1.55927668e+78 -6.17834609e+77]
[ 1.74016932e+85 -1.29120468e+78 -1.60606986e+78 -6.36375541e+77]
[ 1.79239100e+85 -1.32995314e+78 -1.65426728e+78 -6.55472877e+77]
[ 1.84617983e+85 -1.36986442e+78 -1.70391107e+78 -6.75143316e+77]
[ 1.90158283e+85 -1.41097342e+78 -1.75504466e+78 -6.95404056e+77]
[ 1.95864846e+85 -1.45331608e+78 -1.80771274e+78 -7.16272811e+77]
[ 2.01742659e+85 -1.49692943e+78 -1.86196137e+78 -7.37767828e+77]
[ 2.07796864e+85 -1.54185159e+78 -1.91783797e+78 -7.59907901e+77]
[ 2.14032752e+85 -1.58812185e+78 -1.97539140e+78 -7.82712387e+77]
[ 2.204557

[ 1.42042015e+94 -1.05395098e+87 -1.31096093e+87 -5.19444075e+86]
[ 1.46304630e+94 -1.08557956e+87 -1.35030227e+87 -5.35032352e+86]
[ 1.50695165e+94 -1.11815730e+87 -1.39082421e+87 -5.51088426e+86]
[ 1.55217457e+94 -1.15171269e+87 -1.43256221e+87 -5.67626336e+86]
[ 1.59875462e+94 -1.18627505e+87 -1.47555274e+87 -5.84660541e+86]
[ 1.64673251e+94 -1.22187462e+87 -1.51983340e+87 -6.02205934e+86]
[ 1.69615019e+94 -1.25854252e+87 -1.56544290e+87 -6.20277857e+86]
[ 1.74705088e+94 -1.29631080e+87 -1.61242112e+87 -6.38892109e+86]
[ 1.79947907e+94 -1.33521249e+87 -1.66080913e+87 -6.58064967e+86]
[ 1.85348061e+94 -1.37528160e+87 -1.71064925e+87 -6.77813194e+86]
[ 1.90910271e+94 -1.41655316e+87 -1.76198504e+87 -6.98154055e+86]
[ 1.96639400e+94 -1.45906327e+87 -1.81486140e+87 -7.19105337e+86]
[ 2.02540458e+94 -1.50284909e+87 -1.86932456e+87 -7.40685357e+86]
[ 2.08618603e+94 -1.54794890e+87 -1.92542213e+87 -7.62912983e+86]
[ 2.14879152e+94 -1.59440213e+87 -1.98320316e+87 -7.85807650e+86]
[ 2.213275

[ 3.26351627e+103 -2.42152729e+096 -3.01202593e+096 -1.19345969e+096]
[ 3.36145289e+103 -2.49419621e+096 -3.10241544e+096 -1.22927486e+096]
[ 3.46232854e+103 -2.56904589e+096 -3.19551750e+096 -1.26616483e+096]
[ 3.56623143e+103 -2.64614177e+096 -3.29141351e+096 -1.30416186e+096]
[ 3.67325239e+103 -2.72555126e+096 -3.39018731e+096 -1.34329915e+096]
[ 3.78348500e+103 -2.80734380e+096 -3.49192527e+096 -1.38361094e+096]
[ 3.89702564e+103 -2.89159090e+096 -3.59671634e+096 -1.42513247e+096]
[ 4.01397359e+103 -2.97836621e+096 -3.70465214e+096 -1.46790004e+096]
[ 4.13443108e+103 -3.06774560e+096 -3.81582704e+096 -1.51195104e+096]
[ 4.25850345e+103 -3.15980724e+096 -3.93033826e+096 -1.55732400e+096]
[ 4.38629918e+103 -3.25463159e+096 -4.04828590e+096 -1.60405857e+096]
[ 4.51793000e+103 -3.35230159e+096 -4.16977309e+096 -1.65219563e+096]
[ 4.65351100e+103 -3.45290262e+096 -4.29490606e+096 -1.70177726e+096]
[ 4.79316072e+103 -3.55652263e+096 -4.42379421e+096 -1.75284681e+096]
[ 4.93700126e+103 -3

[ 2.90013080e+111 -2.15189547e+104 -2.67664337e+104 -1.06057054e+104]
[ 2.98716239e+111 -2.21647286e+104 -2.75696820e+104 -1.09239777e+104]
[ 3.07680576e+111 -2.28298819e+104 -2.83970355e+104 -1.12518012e+104]
[ 3.16913928e+111 -2.35149961e+104 -2.92492174e+104 -1.15894626e+104]
[ 3.26424369e+111 -2.42206703e+104 -3.01269730e+104 -1.19372570e+104]
[ 3.36220214e+111 -2.49475215e+104 -3.10310695e+104 -1.22954886e+104]
[ 3.46310027e+111 -2.56961851e+104 -3.19622976e+104 -1.26644706e+104]
[ 3.56702632e+111 -2.64673158e+104 -3.29214715e+104 -1.30445255e+104]
[ 3.67407113e+111 -2.72615877e+104 -3.39094297e+104 -1.34359857e+104]
[ 3.78432832e+111 -2.80796954e+104 -3.49270360e+104 -1.38391934e+104]
[ 3.89789426e+111 -2.89223541e+104 -3.59751803e+104 -1.42545012e+104]
[ 4.01486828e+111 -2.97903007e+104 -3.70547789e+104 -1.46822722e+104]
[ 4.13535262e+111 -3.06842939e+104 -3.81667757e+104 -1.51228805e+104]
[ 4.25945265e+111 -3.16051154e+104 -3.93121430e+104 -1.55767111e+104]
[ 4.38727686e+111 -3

[ 5.43769782e+121 -4.03476881e+114 -5.01866254e+114 -1.98855241e+114]
[ 5.60088063e+121 -4.15585037e+114 -5.16927029e+114 -2.04822795e+114]
[ 5.76896048e+121 -4.28056552e+114 -5.32439771e+114 -2.10969433e+114]
[ 5.94208432e+121 -4.40902332e+114 -5.48418043e+114 -2.17300528e+114]
[ 6.12040353e+121 -4.54133608e+114 -5.64875816e+114 -2.23821617e+114]
[ 6.30407402e+121 -4.67761948e+114 -5.81827479e+114 -2.30538401e+114]
[ 6.49325638e+121 -4.81799269e+114 -5.99287854e+114 -2.37456752e+114]
[ 6.68811601e+121 -4.96257843e+114 -6.17272206e+114 -2.44582720e+114]
[ 6.88882329e+121 -5.11150312e+114 -6.35796261e+114 -2.51922534e+114]
[ 7.09555371e+121 -5.26489697e+114 -6.54876213e+114 -2.59482613e+114]
[ 7.30848800e+121 -5.42289410e+114 -6.74528747e+114 -2.67269567e+114]
[ 7.52781236e+121 -5.58563266e+114 -6.94771044e+114 -2.75290204e+114]
[ 7.75371854e+121 -5.75325492e+114 -7.15620803e+114 -2.83551536e+114]
[ 7.98640406e+121 -5.92590745e+114 -7.37096253e+114 -2.92060787e+114]
[ 8.22607237e+121 -6

[ 1.07364459e+130 -7.96643696e+122 -9.90908293e+122 -3.92629123e+122]
[ 1.10586417e+130 -8.20550606e+122 -1.02064499e+123 -4.04411742e+122]
[ 1.13905064e+130 -8.45174952e+122 -1.05127408e+123 -4.16547952e+122]
[ 1.17323302e+130 -8.70538262e+122 -1.08282233e+123 -4.29048364e+122]
[ 1.20844121e+130 -8.96662715e+122 -1.11531733e+123 -4.41923908e+122]
[ 1.24470597e+130 -9.23571150e+122 -1.14878749e+123 -4.55185841e+122]
[ 1.28205902e+130 -9.51287094e+122 -1.18326207e+123 -4.68845758e+122]
[ 1.32053302e+130 -9.79834782e+122 -1.21877122e+123 -4.82915603e+122]
[ 1.36016161e+130 -1.00923917e+123 -1.25534598e+123 -4.97407678e+122]
[ 1.40097943e+130 -1.03952597e+123 -1.29301834e+123 -5.12334653e+122]
[ 1.44302218e+130 -1.07072167e+123 -1.33182122e+123 -5.27709580e+122]
[ 1.48632661e+130 -1.10285353e+123 -1.37178857e+123 -5.43545902e+122]
[ 1.53093059e+130 -1.13594966e+123 -1.41295531e+123 -5.59857464e+122]
[ 1.57687311e+130 -1.17003899e+123 -1.45535745e+123 -5.76658528e+122]
[ 1.62419435e+130 -1

[ 1.88339329e+138 -1.39747679e+131 -1.73825683e+131 -6.88752188e+130]
[ 1.93991306e+138 -1.43941443e+131 -1.79042111e+131 -7.09421323e+130]
[ 1.99812895e+138 -1.48261059e+131 -1.84415083e+131 -7.30710730e+130]
[ 2.05809188e+138 -1.52710305e+131 -1.89949294e+131 -7.52639023e+130]
[ 2.11985427e+138 -1.57293071e+131 -1.95649585e+131 -7.75225373e+130]
[ 2.18347012e+138 -1.62013364e+131 -2.01520939e+131 -7.98489529e+130]
[ 2.24899506e+138 -1.66875310e+131 -2.07568490e+131 -8.22451832e+130]
[ 2.31648636e+138 -1.71883161e+131 -2.13797524e+131 -8.47133233e+130]
[ 2.38600305e+138 -1.77041296e+131 -2.20213490e+131 -8.72555311e+130]
[ 2.45760590e+138 -1.82354224e+131 -2.26821995e+131 -8.98740293e+130]
[ 2.53135752e+138 -1.87826590e+131 -2.33628818e+131 -9.25711075e+130]
[ 2.60732239e+138 -1.93463179e+131 -2.40639912e+131 -9.53491238e+130]
[ 2.68556694e+138 -1.99268920e+131 -2.47861405e+131 -9.82105071e+130]
[ 2.76615956e+138 -2.05248888e+131 -2.55299611e+131 -1.01157759e+131]
[ 2.84917074e+138 -2

[ 2.47652970e+148 -1.83758369e+141 -2.28568546e+141 -9.05660681e+140]
[ 2.55084922e+148 -1.89272873e+141 -2.35427783e+141 -9.32839140e+140]
[ 2.62739903e+148 -1.94952864e+141 -2.42492862e+141 -9.60833213e+140]
[ 2.70624606e+148 -2.00803310e+141 -2.49769961e+141 -9.89667375e+140]
[ 2.78745926e+148 -2.06829325e+141 -2.57265443e+141 -1.01936684e+141]
[ 2.87110963e+148 -2.13036178e+141 -2.64985860e+141 -1.04995757e+141]
[ 2.95727031e+148 -2.19429295e+141 -2.72937964e+141 -1.08146631e+141]
[ 3.04601663e+148 -2.26014267e+141 -2.81128706e+141 -1.11392061e+141]
[ 3.13742618e+148 -2.32796851e+141 -2.89565249e+141 -1.14734886e+141]
[ 3.23157889e+148 -2.39782977e+141 -2.98254969e+141 -1.18178027e+141]
[ 3.32855709e+148 -2.46978754e+141 -3.07205463e+141 -1.21724495e+141]
[ 3.42844555e+148 -2.54390473e+141 -3.16424558e+141 -1.25377391e+141]
[ 3.53133162e+148 -2.62024613e+141 -3.25920313e+141 -1.29139909e+141]
[ 3.63730526e+148 -2.69887851e+141 -3.35701031e+141 -1.33015338e+141]
[ 3.74645911e+148 -2

[ 1.64967117e+158 -1.22405511e+151 -1.52254561e+151 -6.03280597e+150]
[ 1.69917705e+158 -1.26078844e+151 -1.56823650e+151 -6.21384770e+150]
[ 1.75016857e+158 -1.29862412e+151 -1.61529855e+151 -6.40032240e+150]
[ 1.80269032e+158 -1.33759523e+151 -1.66377292e+151 -6.59239313e+150]
[ 1.85678822e+158 -1.37773585e+151 -1.71370198e+151 -6.79022781e+150]
[ 1.91250958e+158 -1.41908107e+151 -1.76512938e+151 -6.99399942e+150]
[ 1.96990311e+158 -1.46166703e+151 -1.81810010e+151 -7.20388612e+150]
[ 2.02901900e+158 -1.50553099e+151 -1.87266045e+151 -7.42007142e+150]
[ 2.08990892e+158 -1.55071128e+151 -1.92885813e+151 -7.64274434e+150]
[ 2.15262613e+158 -1.59724741e+151 -1.98674227e+151 -7.87209958e+150]
[ 2.21722545e+158 -1.64518007e+151 -2.04636349e+151 -8.10833766e+150]
[ 2.28376336e+158 -1.69455117e+151 -2.10777392e+151 -8.35166514e+150]
[ 2.35229805e+158 -1.74540386e+151 -2.17102724e+151 -8.60229476e+150]
[ 2.42288943e+158 -1.79778263e+151 -2.23617877e+151 -8.86044566e+150]
[ 2.49559922e+158 -1

[ 7.64930113e+165 -5.67577726e+158 -7.05983714e+158 -2.79733017e+158]
[ 7.87885314e+165 -5.84610472e+158 -7.27169960e+158 -2.88127676e+158]
[ 8.11529389e+165 -6.02154363e+158 -7.48991996e+158 -2.96774255e+158]
[ 8.35883012e+165 -6.20224738e+158 -7.71468901e+158 -3.05680314e+158]
[ 8.60967476e+165 -6.38837396e+158 -7.94620327e+158 -3.14853639e+158]
[ 8.86804713e+165 -6.58008612e+158 -8.18466517e+158 -3.24302252e+158]
[ 9.13417314e+165 -6.77755148e+158 -8.43028320e+158 -3.34034413e+158]
[ 9.40828547e+165 -6.98094267e+158 -8.68327211e+158 -3.44058632e+158]
[ 9.69062378e+165 -7.19043755e+158 -8.94385311e+158 -3.54383673e+158]
[ 9.98143493e+165 -7.40621926e+158 -9.21225402e+158 -3.65018564e+158]
[ 1.02809732e+166 -7.62847649e+158 -9.48870952e+158 -3.75972603e+158]
[ 1.05895005e+166 -7.85740356e+158 -9.77346132e+158 -3.87255367e+158]
[ 1.09072865e+166 -8.09320062e+158 -1.00667584e+159 -3.98876722e+158]
[ 1.12346091e+166 -8.33607384e+158 -1.03688572e+159 -4.10846829e+158]
[ 1.15717546e+166 -8

[ 6.43114531e+174 -4.77190631e+167 -5.93555382e+167 -2.35185366e+167]
[ 6.62414102e+174 -4.91510902e+167 -6.11367706e+167 -2.42243170e+167]
[ 6.82292844e+174 -5.06260917e+167 -6.29714569e+167 -2.49512776e+167]
[ 7.02768138e+174 -5.21453574e+167 -6.48612013e+167 -2.57000540e+167]
[ 7.23857886e+174 -5.37102156e+167 -6.68076560e+167 -2.64713007e+167]
[ 7.45580528e+174 -5.53220344e+167 -6.88125230e+167 -2.72656923e+167]
[ 7.67955056e+174 -5.69822232e+167 -7.08775551e+167 -2.80839231e+167]
[ 7.91001033e+174 -5.86922334e+167 -7.30045579e+167 -2.89267087e+167]
[ 8.14738610e+174 -6.04535603e+167 -7.51953910e+167 -2.97947859e+167]
[ 8.39188540e+174 -6.22677438e+167 -7.74519701e+167 -3.06889137e+167]
[ 8.64372201e+174 -6.41363701e+167 -7.97762680e+167 -3.16098739e+167]
[ 8.90311613e+174 -6.60610730e+167 -8.21703171e+167 -3.25584716e+167]
[ 9.17029454e+174 -6.80435354e+167 -8.46362104e+167 -3.35355364e+167]
[ 9.44549085e+174 -7.00854905e+167 -8.71761041e+167 -3.45419224e+167]
[ 9.72894568e+174 -7

[ 2.29381680e+183 -1.70201081e+176 -2.11705262e+176 -8.38843030e+175]
[ 2.36265318e+183 -1.75308737e+176 -2.18058439e+176 -8.64016322e+175]
[ 2.43355531e+183 -1.80569671e+176 -2.24602273e+176 -8.89945054e+175]
[ 2.50658519e+183 -1.85988484e+176 -2.31342484e+176 -9.16651895e+175]
[ 2.58180665e+183 -1.91569913e+176 -2.38284965e+176 -9.44160196e+175]
[ 2.65928548e+183 -1.97318837e+176 -2.45435787e+176 -9.72494009e+175]
[ 2.73908941e+183 -2.03240285e+176 -2.52801202e+176 -1.00167811e+176]
[ 2.82128823e+183 -2.09339432e+176 -2.60387649e+176 -1.03173800e+176]
[ 2.90595378e+183 -2.15621612e+176 -2.68201763e+176 -1.06269999e+176]
[ 2.99316012e+183 -2.22092317e+176 -2.76250374e+176 -1.09459112e+176]
[ 3.08298347e+183 -2.28757205e+176 -2.84540520e+176 -1.12743930e+176]
[ 3.17550239e+183 -2.35622104e+176 -2.93079450e+176 -1.16127323e+176]
[ 3.27079775e+183 -2.42693014e+176 -3.01874630e+176 -1.19612251e+176]
[ 3.36895289e+183 -2.49976120e+176 -3.10933748e+176 -1.23201759e+176]
[ 3.47005361e+183 -2

[ 1.52796207e+193 -1.13374702e+186 -1.41021554e+186 -5.58771883e+185]
[ 1.57381550e+193 -1.16777024e+186 -1.45253546e+186 -5.75540369e+185]
[ 1.62104498e+193 -1.20281449e+186 -1.49612538e+186 -5.92812071e+185]
[ 1.66969180e+193 -1.23891040e+186 -1.54102342e+186 -6.10602088e+185]
[ 1.71979848e+193 -1.27608953e+186 -1.58726882e+186 -6.28925975e+185]
[ 1.77140884e+193 -1.31438439e+186 -1.63490202e+186 -6.47799754e+185]
[ 1.82456800e+193 -1.35382846e+186 -1.68396468e+186 -6.67239926e+185]
[ 1.87932244e+193 -1.39445623e+186 -1.73449968e+186 -6.87263489e+185]
[ 1.93572005e+193 -1.43630322e+186 -1.78655122e+186 -7.07887949e+185]
[ 1.99381011e+193 -1.47940601e+186 -1.84016480e+186 -7.29131341e+185]
[ 2.05364343e+193 -1.52380231e+186 -1.89538730e+186 -7.51012236e+185]
[ 2.11527233e+193 -1.56953091e+186 -1.95226700e+186 -7.73549767e+185]
[ 2.17875068e+193 -1.61663181e+186 -2.01085363e+186 -7.96763639e+185]
[ 2.24413398e+193 -1.66514619e+186 -2.07119842e+186 -8.20674149e+185]
[ 2.31147941e+193 -1

[ 1.62140630e+201 -1.20308259e+194 -1.49645886e+194 -5.92944205e+193]
[ 1.67006396e+201 -1.23918655e+194 -1.54136690e+194 -6.10738187e+193]
[ 1.72018181e+201 -1.27637396e+194 -1.58762261e+194 -6.29066159e+193]
[ 1.77180367e+201 -1.31467736e+194 -1.63526643e+194 -6.47944145e+193]
[ 1.82497469e+201 -1.35413022e+194 -1.68434003e+194 -6.67388650e+193]
[ 1.87974133e+201 -1.39476704e+194 -1.73488629e+194 -6.87416676e+193]
[ 1.93615151e+201 -1.43662336e+194 -1.78694943e+194 -7.08045733e+193]
[ 1.99425452e+201 -1.47973576e+194 -1.84057496e+194 -7.29293860e+193]
[ 2.05410118e+201 -1.52414195e+194 -1.89580977e+194 -7.51179632e+193]
[ 2.11574381e+201 -1.56988075e+194 -1.95270215e+194 -7.73722187e+193]
[ 2.17923631e+201 -1.61699215e+194 -2.01130184e+194 -7.96941233e+193]
[ 2.24463418e+201 -1.66551734e+194 -2.07166008e+194 -8.20857072e+193]
[ 2.31199462e+201 -1.71549875e+194 -2.13382964e+194 -8.45490615e+193]
[ 2.38137651e+201 -1.76698007e+194 -2.19786489e+194 -8.70863399e+193]
[ 2.45284053e+201 -1

[ 8.94430203e+207 -6.63666722e+200 -8.25504378e+200 -3.27090875e+200]
[ 9.21271642e+207 -6.83583055e+200 -8.50277384e+200 -3.36906721e+200]
[ 9.48918579e+207 -7.04097067e+200 -8.75793816e+200 -3.47017136e+200]
[ 9.77395188e+207 -7.25226696e+200 -9.02075985e+200 -3.57430961e+200]
[ 1.00672637e+208 -7.46990415e+200 -9.29146870e+200 -3.68157299e+200]
[ 1.03693776e+208 -7.69407253e+200 -9.57030139e+200 -3.79205530e+200]
[ 1.06805579e+208 -7.92496810e+200 -9.85750173e+200 -3.90585313e+200]
[ 1.10010765e+208 -8.16279274e+200 -1.01533208e+201 -4.02306599e+200]
[ 1.13312137e+208 -8.40775439e+200 -1.04580173e+201 -4.14379634e+200]
[ 1.16712582e+208 -8.66006722e+200 -1.07718576e+201 -4.26814976e+200]
[ 1.20215073e+208 -8.91995185e+200 -1.10951161e+201 -4.39623497e+200]
[ 1.23822672e+208 -9.18763550e+200 -1.14280754e+201 -4.52816396e+200]
[ 1.27538533e+208 -9.46335220e+200 -1.17710267e+201 -4.66405207e+200]
[ 1.31365906e+208 -9.74734304e+200 -1.21242697e+201 -4.80401812e+200]
[ 1.35308136e+208 -1

[ 2.22897216e+215 -1.65389613e+208 -2.05720499e+208 -8.15129511e+207]
[ 2.29586259e+215 -1.70352879e+208 -2.11894077e+208 -8.39591172e+207]
[ 2.36476037e+215 -1.75465090e+208 -2.18252920e+208 -8.64786916e+207]
[ 2.43572574e+215 -1.80730717e+208 -2.24802590e+208 -8.90738773e+207]
[ 2.50882075e+215 -1.86154362e+208 -2.31548812e+208 -9.17469433e+207]
[ 2.58410930e+215 -1.91740769e+208 -2.38497485e+208 -9.45002268e+207]
[ 2.66165723e+215 -1.97494821e+208 -2.45654685e+208 -9.73361351e+207]
[ 2.74153234e+215 -2.03421550e+208 -2.53026669e+208 -1.00257148e+208]
[ 2.82380446e+215 -2.09526136e+208 -2.60619882e+208 -1.03265818e+208]
[ 2.90854553e+215 -2.15813919e+208 -2.68440965e+208 -1.06364778e+208]
[ 2.99582964e+215 -2.22290396e+208 -2.76496755e+208 -1.09556736e+208]
[ 3.08573311e+215 -2.28961228e+208 -2.84794295e+208 -1.12844483e+208]
[ 3.17833454e+215 -2.35832249e+208 -2.93340840e+208 -1.16230894e+208]
[ 3.27371489e+215 -2.42909466e+208 -3.02143864e+208 -1.19718930e+208]
[ 3.37195757e+215 -2

[ 2.57507816e+222 -1.91070659e+215 -2.37663966e+215 -9.41699602e+214]
[ 2.65235507e+222 -1.96804601e+215 -2.44796152e+215 -9.69959573e+214]
[ 2.73195102e+222 -2.02710616e+215 -2.52142372e+215 -9.99067613e+214]
[ 2.81393561e+222 -2.08793869e+215 -2.59709048e+215 -1.02904917e+215]
[ 2.89838052e+222 -2.15059676e+215 -2.67502797e+215 -1.05993046e+215]
[ 2.98535959e+222 -2.21513518e+215 -2.75530433e+215 -1.09173849e+215]
[ 3.07494885e+222 -2.28161037e+215 -2.83798974e+215 -1.12450106e+215]
[ 3.16722665e+222 -2.35008044e+215 -2.92315650e+215 -1.15824682e+215]
[ 3.26227366e+222 -2.42060528e+215 -3.01087908e+215 -1.19300527e+215]
[ 3.36017299e+222 -2.49324652e+215 -3.10123418e+215 -1.22880681e+215]
[ 3.46101024e+222 -2.56806770e+215 -3.19430079e+215 -1.26568273e+215]
[ 3.56487356e+222 -2.64513423e+215 -3.29016028e+215 -1.30366529e+215]
[ 3.67185377e+222 -2.72451349e+215 -3.38889648e+215 -1.34278768e+215]
[ 3.78204441e+222 -2.80627489e+215 -3.49059570e+215 -1.38308412e+215]
[ 3.89554182e+222 -2

[ 8.43634506e+231 -6.25976343e+224 -7.78623056e+224 -3.08515016e+224]
[ 8.68951589e+231 -6.44761604e+224 -8.01989175e+224 -3.17773409e+224]
[ 8.95028426e+231 -6.64110603e+224 -8.26056501e+224 -3.27309643e+224]
[ 9.21887817e+231 -6.84040256e+224 -8.50846076e+224 -3.37132055e+224]
[ 9.49553245e+231 -7.04567989e+224 -8.76379574e+224 -3.47249232e+224]
[ 9.78048901e+231 -7.25711750e+224 -9.02679322e+224 -3.57670022e+224]
[ 1.00739970e+232 -7.47490025e+224 -9.29768312e+224 -3.68403534e+224]
[ 1.03763130e+232 -7.69921856e+224 -9.57670231e+224 -3.79459155e+224]
[ 1.06877014e+232 -7.93026856e+224 -9.86409473e+224 -3.90846549e+224]
[ 1.10084343e+232 -8.16825227e+224 -1.01601117e+225 -4.02575674e+224]
[ 1.13387924e+232 -8.41337775e+224 -1.04650119e+225 -4.14656784e+224]
[ 1.16790643e+232 -8.66585934e+224 -1.07790621e+225 -4.27100443e+224]
[ 1.20295477e+232 -8.92591779e+224 -1.11025368e+225 -4.39917531e+224]
[ 1.23905488e+232 -9.19378047e+224 -1.14357188e+225 -4.53119253e+224]
[ 1.27623835e+232 -9

[ 1.57006383e+240 -1.16498651e+233 -1.44907290e+233 -5.74168393e+232]
[ 1.61718073e+240 -1.19994721e+233 -1.49255891e+233 -5.91398922e+232]
[ 1.66571157e+240 -1.23595708e+233 -1.53734991e+233 -6.09146531e+232]
[ 1.71569881e+240 -1.27304758e+233 -1.58348508e+233 -6.27426738e+232]
[ 1.76718614e+240 -1.31125115e+233 -1.63100473e+233 -6.46255525e+232]
[ 1.82021858e+240 -1.35060119e+233 -1.67995044e+233 -6.65649355e+232]
[ 1.87484250e+240 -1.39113211e+233 -1.73036497e+233 -6.85625186e+232]
[ 1.93110566e+240 -1.43287935e+233 -1.78229243e+233 -7.06200482e+232]
[ 1.98905726e+240 -1.47587940e+233 -1.83577820e+233 -7.27393233e+232]
[ 2.04874795e+240 -1.52016986e+233 -1.89086906e+233 -7.49221969e+232]
[ 2.11022993e+240 -1.56578945e+233 -1.94761317e+233 -7.71705775e+232]
[ 2.17355696e+240 -1.61277807e+233 -2.00606015e+233 -7.94864309e+232]
[ 2.23878440e+240 -1.66117680e+233 -2.06626109e+233 -8.18717821e+232]
[ 2.30596929e+240 -1.71102795e+233 -2.12826863e+233 -8.43287166e+232]
[ 2.37517036e+240 -1

[ 1.88225663e+249 -1.39663339e+242 -1.73720776e+242 -6.88336514e+241]
[ 1.93874229e+249 -1.43854572e+242 -1.78934057e+242 -7.08993176e+241]
[ 1.99692305e+249 -1.48171581e+242 -1.84303785e+242 -7.30269734e+241]
[ 2.05684979e+249 -1.52618142e+242 -1.89834657e+242 -7.52184793e+241]
[ 2.11857491e+249 -1.57198142e+242 -1.95531507e+242 -7.74757512e+241]
[ 2.18215236e+249 -1.61915586e+242 -2.01399318e+242 -7.98007628e+241]
[ 2.24763775e+249 -1.66774598e+242 -2.07443219e+242 -8.21955469e+241]
[ 2.31508832e+249 -1.71779427e+242 -2.13668494e+242 -8.46621974e+241]
[ 2.38456306e+249 -1.76934448e+242 -2.20080587e+242 -8.72028709e+241]
[ 2.45612270e+249 -1.82244170e+242 -2.26685104e+242 -8.98197889e+241]
[ 2.52982981e+249 -1.87713233e+242 -2.33487820e+242 -9.25152394e+241]
[ 2.60574883e+249 -1.93346421e+242 -2.40494682e+242 -9.52915791e+241]
[ 2.68394615e+249 -1.99148658e+242 -2.47711816e+242 -9.81512354e+241]
[ 2.76449014e+249 -2.05125017e+242 -2.55145534e+242 -1.01096709e+242]
[ 2.84745122e+249 -2

[ 1.49163617e+258 -1.10679323e+251 -1.37668897e+251 -5.45487595e+250]
[ 1.53639949e+258 -1.14000758e+251 -1.41800277e+251 -5.61857427e+250]
[ 1.58250613e+258 -1.17421868e+251 -1.46055638e+251 -5.78718509e+250]
[ 1.62999641e+258 -1.20945644e+251 -1.50438700e+251 -5.96085585e+250]
[ 1.67891185e+258 -1.24575168e+251 -1.54953296e+251 -6.13973839e+250]
[ 1.72929522e+258 -1.28313611e+251 -1.59603373e+251 -6.32398911e+250]
[ 1.78119057e+258 -1.32164243e+251 -1.64392997e+251 -6.51376911e+250]
[ 1.83464328e+258 -1.36130431e+251 -1.69326355e+251 -6.70924432e+250]
[ 1.88970008e+258 -1.40215643e+251 -1.74407761e+251 -6.91058565e+250]
[ 1.94640911e+258 -1.44423450e+251 -1.79641657e+251 -7.11796914e+250]
[ 2.00481995e+258 -1.48757531e+251 -1.85032621e+251 -7.33157611e+250]
[ 2.06498367e+258 -1.53221676e+251 -1.90585365e+251 -7.55159333e+250]
[ 2.12695288e+258 -1.57819788e+251 -1.96304744e+251 -7.77821317e+250]
[ 2.19078176e+258 -1.62555887e+251 -2.02195758e+251 -8.01163376e+250]
[ 2.25652611e+258 -1

[ 1.40629750e+266 -1.04347198e+259 -1.29792659e+259 -5.14279456e+258]
[ 1.44849984e+266 -1.07478609e+259 -1.33687677e+259 -5.29712746e+258]
[ 1.49196865e+266 -1.10703992e+259 -1.37699582e+259 -5.45609181e+258]
[ 1.53674194e+266 -1.14026168e+259 -1.41831883e+259 -5.61982661e+258]
[ 1.58285886e+266 -1.17448041e+259 -1.46088193e+259 -5.78847502e+258]
[ 1.63035973e+266 -1.20972603e+259 -1.50472232e+259 -5.96218449e+258]
[ 1.67928607e+266 -1.24602935e+259 -1.54987834e+259 -6.14110690e+258]
[ 1.72968067e+266 -1.28342211e+259 -1.59638948e+259 -6.32539869e+258]
[ 1.78158759e+266 -1.32193702e+259 -1.64429639e+259 -6.51522099e+258]
[ 1.83505221e+266 -1.36160774e+259 -1.69364097e+259 -6.71073977e+258]
[ 1.89012129e+266 -1.40246896e+259 -1.74446635e+259 -6.91212597e+258]
[ 1.94684295e+266 -1.44455641e+259 -1.79681699e+259 -7.11955569e+258]
[ 2.00526681e+266 -1.48790688e+259 -1.85073864e+259 -7.33321028e+258]
[ 2.06544395e+266 -1.53255828e+259 -1.90627845e+259 -7.55327654e+258]
[ 2.12742697e+266 -1

[ 2.40399574e+275 -1.78376352e+268 -2.21874105e+268 -8.79135191e+267]
[ 2.47613854e+275 -1.83729344e+268 -2.28532444e+268 -9.05517633e+267]
[ 2.55044632e+275 -1.89242977e+268 -2.35390598e+268 -9.32691800e+267]
[ 2.62698404e+275 -1.94922072e+268 -2.42454561e+268 -9.60681451e+267]
[ 2.70581862e+275 -2.00771594e+268 -2.49730511e+268 -9.89511059e+267]
[ 2.78701899e+275 -2.06796657e+268 -2.57224808e+268 -1.01920583e+268]
[ 2.87065614e+275 -2.13002529e+268 -2.64944006e+268 -1.04979173e+268]
[ 2.95680321e+275 -2.19394637e+268 -2.72894854e+268 -1.08129549e+268]
[ 3.04553551e+275 -2.25978569e+268 -2.81084303e+268 -1.11374467e+268]
[ 3.13693063e+275 -2.32760081e+268 -2.89519513e+268 -1.14716764e+268]
[ 3.23106847e+275 -2.39745104e+268 -2.98207860e+268 -1.18159361e+268]
[ 3.32803135e+275 -2.46939744e+268 -3.07156941e+268 -1.21705269e+268]
[ 3.42790404e+275 -2.54350292e+268 -3.16374579e+268 -1.25357588e+268]
[ 3.53077386e+275 -2.61983227e+268 -3.25868834e+268 -1.29119511e+268]
[ 3.63673075e+275 -2

[ 7.15384231e+282 -5.30814708e+275 -6.60255895e+275 -2.61614213e+275]
[ 7.36852582e+282 -5.46744213e+275 -6.80069870e+275 -2.69465135e+275]
[ 7.58965189e+282 -5.63151755e+275 -7.00478454e+275 -2.77551660e+275]
[ 7.81741384e+282 -5.80051680e+275 -7.21499490e+275 -2.85880857e+275]
[ 8.05201083e+282 -5.97458764e+275 -7.43151357e+275 -2.94460010e+275]
[ 8.29364797e+282 -6.15388226e+275 -7.65452987e+275 -3.03296619e+275]
[ 8.54253652e+282 -6.33855743e+275 -7.88423878e+275 -3.12398411e+275]
[ 8.79889410e+282 -6.52877462e+275 -8.12084115e+275 -3.21773343e+275]
[ 9.06294486e+282 -6.72470013e+275 -8.36454385e+275 -3.31429613e+275]
[ 9.33491966e+282 -6.92650529e+275 -8.61555996e+275 -3.41375663e+275]
[ 9.61505630e+282 -7.13436652e+275 -8.87410895e+275 -3.51620189e+275]
[ 9.90359971e+282 -7.34846557e+275 -9.14041687e+275 -3.62172149e+275]
[ 1.02008022e+283 -7.56898964e+275 -9.41471656e+275 -3.73040768e+275]
[ 1.05069235e+283 -7.79613153e+275 -9.69724787e+275 -3.84235550e+275]
[ 1.08222315e+283 -8

[ 1.54926542e+292 -1.14955409e+285 -1.42987723e+285 -5.66562464e+284]
[ 1.59575816e+292 -1.18405168e+285 -1.47278719e+285 -5.83564743e+284]
[ 1.64364613e+292 -1.21958453e+285 -1.51698486e+285 -6.01077252e+284]
[ 1.69297119e+292 -1.25618370e+285 -1.56250887e+285 -6.19115303e+284]
[ 1.74377647e+292 -1.29388119e+285 -1.60939904e+285 -6.37694668e+284]
[ 1.79610640e+292 -1.33270997e+285 -1.65769637e+285 -6.56831592e+284]
[ 1.85000673e+292 -1.37270398e+285 -1.70744307e+285 -6.76542805e+284]
[ 1.90552458e+292 -1.41389820e+285 -1.75868265e+285 -6.96845543e+284]
[ 1.96270849e+292 -1.45632863e+285 -1.81145991e+285 -7.17757556e+284]
[ 2.02160847e+292 -1.50003238e+285 -1.86582098e+285 -7.39297130e+284]
[ 2.08227601e+292 -1.54504766e+285 -1.92181341e+285 -7.61483096e+284]
[ 2.14476415e+292 -1.59141383e+285 -1.97948615e+285 -7.84334853e+284]
[ 2.20912754e+292 -1.63917142e+285 -2.03888961e+285 -8.07872381e+284]
[ 2.27542244e+292 -1.68836220e+285 -2.10007575e+285 -8.32116259e+284]
[ 2.34370681e+292 -1

[ 1.06296978e+302 -7.88722996e+294 -9.81056100e+294 -3.88725374e+294]
[ 1.09486901e+302 -8.12392210e+294 -1.01049714e+295 -4.00390843e+294]
[ 1.12772553e+302 -8.36771726e+294 -1.04082170e+295 -4.12406388e+294]
[ 1.16156805e+302 -8.61882859e+294 -1.07205627e+295 -4.24782513e+294]
[ 1.19642617e+302 -8.87747567e+294 -1.10422819e+295 -4.37530041e+294]
[ 1.23233037e+302 -9.14388462e+294 -1.13736557e+295 -4.50660116e+294]
[ 1.26931204e+302 -9.41828839e+294 -1.17149739e+295 -4.64184218e+294]
[ 1.30740351e+302 -9.70092688e+294 -1.20665348e+295 -4.78114173e+294]
[ 1.34663808e+302 -9.99204723e+294 -1.24286460e+295 -4.92462159e+294]
[ 1.38705007e+302 -1.02919040e+295 -1.28016239e+295 -5.07240721e+294]
[ 1.42867481e+302 -1.06007593e+295 -1.31857947e+295 -5.22462782e+294]
[ 1.47154868e+302 -1.09188832e+295 -1.35814944e+295 -5.38141649e+294]
[ 1.51570918e+302 -1.12465538e+295 -1.39890688e+295 -5.54291032e+294]
[ 1.56119491e+302 -1.15840577e+295 -1.44088743e+295 -5.70925050e+294]
[ 1.60804565e+302 -1